# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b9307dfbf9fe7e11bf5a5044bc3a6d845f396a69fbeef6b6ceeea86c3d6c6988ef6f930f17c6d3e7dcde8c7f1799e3e800f0ad41f25297d889b1de5e88b47bd

test:
  secret_key_base: cd4b268c6ad45ec398f0a53786a7a4caae8a3908144b2071cd50b6857c2ae17359334a6556fabdb66f4b53bba26e6d0f41522c97914f3a7ba4643ccc464f268f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
